name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers workflow on version tags, e.g., v1.0.0

permissions:
  contents: write  # Grant permission to create releases and upload assets

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21' # Adjust this version to your project requirements

    - name: Build binary
      run: |
        mkdir -p dist
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/${{ matrix.goos }}_${{ matrix.goarch }}/videocropanalyzer

    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: dist/**

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download binaries
      uses: actions/download-artifact@v3
      with:
        name: binaries
        path: ./dist

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/**
        tag_name: ${{ github.ref }}   # Use the tag that triggered the workflow
        name: Release ${{ github.ref }}  # Set the name of the release
        body: "Release notes for ${{ github.ref }}"  # Optional: Add release notes
        draft: false  # Set to false to publish the release
        prerelease: false  # Set to false to mark as a full release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
