name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on tags like v1.0.0, v1.2.3, etc.

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows, macos]
        arch: [amd64, arm64]
        include:
          - os: linux
            ext: ""
          - os: windows
            ext: ".exe"
          - os: macos
            ext: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'  # Specify your Go version here

      - name: Build binaries
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o videocropanalyzer_${{ matrix.os }}_${{ matrix.arch }}${{ matrix.ext }}

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: videocropanalyzer-${{ matrix.os }}-${{ matrix.arch }}
          path: videocropanalyzer_${{ matrix.os }}_${{ matrix.arch }}${{ matrix.ext }}

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/
          asset_name: videocropanalyzer-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}
          asset_content_type: application/octet-stream
