name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on tags like v1.0.0, v1.2.3, etc.

permissions: write-all

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]
        include:
          - os: linux
            ext: ""
          - os: windows
            ext: ".exe"
          - os: darwin
            ext: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'  # Specify your Go version here

      - name: Build binaries
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o videocropanalyzer_${{ matrix.os }}_${{ matrix.arch }}${{ matrix.ext }}

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: videocropanalyzer_${{ matrix.os }}_${{ matrix.arch }}
          path: videocropanalyzer_${{ matrix.os }}_${{ matrix.arch }}${{ matrix.ext }}

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: List downloaded artifacts
        run: ls -la ./artifacts/videocropanalyzer_linux_amd64

      - name: Upload Release Asset (Linux amd64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/videocropanalyzer_linux_amd64/videocropanalyzer_linux_amd64
          asset_name: videocropanalyzer_linux_amd64
          asset_content_type: application/octet-stream

      - name: Upload Release Asset (Linux arm64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/videocropanalyzer_linux_arm64/videocropanalyzer_linux_arm64
          asset_name: videocropanalyzer_linux_arm64
          asset_content_type: application/octet-stream

      - name: Upload Release Asset (Windows amd64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/videocropanalyzer_windows_amd64/videocropanalyzer_windows_amd64.exe
          asset_name: videocropanalyzer_windows_amd64.exe
          asset_content_type: application/octet-stream

      - name: Upload Release Asset (Windows arm64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/videocropanalyzer_windows_arm64/videocropanalyzer_windows_arm64.exe
          asset_name: videocropanalyzer_windows_arm64.exe
          asset_content_type: application/octet-stream

      - name: Upload Release Asset (macOS amd64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/videocropanalyzer_darwin_amd64/videocropanalyzer_darwin_amd64
          asset_name: videocropanalyzer_darwin_amd64
          asset_content_type: application/octet-stream

      - name: Upload Release Asset (macOS arm64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/videocropanalyzer_darwin_arm64/videocropanalyzer_darwin_arm64
          asset_name: videocropanalyzer_darwin_arm64
          asset_content_type: application/octet-stream